name: patents4j
channels:
- defaults
dependencies:
- jupyter
- numpy
- numexpr
- matplotlib
- pandas
- pip
- python
- python-dateutil
- setuptools
- pip:
  - awscli
  - flake8
  - botocore
  - chardet
  - click
  - coverage
  - daff
  - graphviz
  - munch
  - pandoc
  - pytest
  - pytest-runner
  - python-dotenv
  - pyyaml
  - requests
  - snakemake
  - sphinx
  - tqdm
